@startuml

actor Client
control QSM
queue StringDequeQueue
control State
Client -> QSM : Calls "loop()"
loop Until Queue Empty
QSM -> StringDequeQueue : Calls "get()"
alt Receives None
QSM -> Client : Returns
else Received a state name
QSM -> QSM : Checks if state exists
alt State Does not Exist
QSM -> Client : Throw NoSuchStateException
else State Exists
QSM -> QSM : Generates StateContext
QSM -> State : Calls "execute()"
State -> StringDequeQueue : May enqueue more states
State -> QSM : May modify context
State -> QSM : Returns StateContent
end
end
end

@enduml
